### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by gomorizsolt** [c-hive/team-contribution-calendar#4]
- [x] Basic setup(#5, resolved by #2 and #3).
- [x] Elaborate the entry point(#6, resolved by #8).
- [ ] Session: integration testing, presented by @thisismydesign. :)
- [x] Empty calendar, styles(#7, resolved by #10).
- [x] Pre-define an empty user(#1, resolved by #11 and #14).
- [x] Handle GH / GL users(#12, resolved by #13, #14 and #16).
- [x] Hover effect(#18, resolved by #23).

**Comment by thisismydesign** [comment]
We've released the MVP so I'm closing this :)
